### PR TITLE
feat(workspace): feature-select the catalogs, rename the test driver, drop the parked theme

### PR DESCRIPTION
**Pull request by vanyastaff**
Closes #569 — the last preflight blocker on the Runtime.1 critical path (`#567 → (#568, #569) → #550`). Breaking changes are deliberate: these are accidental package contracts, and they get expensive to change the moment conformance work freezes them.

### The facade is feature-selective, Material-first

`flui-material` and `flui-cupertino` become `optional = true`; `flui-localizations` is **added** as an optional dependency (it was absent entirely, so the localizations criterion meant adding an edge, not un-gating one).

```toml
default = ["material"]
material = ["dep:flui-material"]
cupertino = ["dep:flui-cupertino"]
localizations = ["dep:flui-localizations"]
hot-reload = ["flui-app/hot-reload"]
golden = ["material", "cupertino"]   # the golden suite renders both demo trees
```

This is exactly the shape [the workspace boundary review](https://github.com/vanyastaff/flui/blob/main/docs/research/2026-08-01-workspace-boundary-and-logging-review.md) prescribes, so no reconstruction guesswork was needed.

`flui::material` / `flui::cupertino` / `flui::localizations` are `#[cfg]`-gated re-exports — **absent, not empty**, when their feature is off. `flui::prelude` splits into an always-present base half (`flui_widgets::prelude` + `run_app`) and a `cfg(feature = "material")` Material half, so a catalog-free application still writes ordinary screens off `use flui::prelude::*`.

`required-features` was added to the catalog-dependent examples and tests (`material_demo`, `cupertino_demo`, `screenshot`, `golden_screenshots`), since they are otherwise auto-discovered and would break `--no-default-features`.

### Hot reload leaves the ordinary production graph

`flui-hot-reload` is optional in `flui-app` behind a `hot-reload` feature. Rather than fork the platform bootstraps, everything that would name a `flui_hot_reload` item goes through a new `app::hot_reload` seam with a real and an inert implementation — `WorkerReload` (desktop) and `ScenePlugin` (Android). The inert implementations name no `flui_hot_reload` item at all, which is what makes the absent dependency compile. The internal API that carries `HotReloadTier` (`UiCommand::HotReload`, `UiCommandSender::request_hot_reload`, `UiRealm::apply_hot_reload`, `PresentationState::apply_hot_reload`, `AppBinding::perform_hot_reload_entered`) is `cfg`-gated; all of it is `pub(crate)`, so the public surface is unchanged.

Four `UiRealm` inbox tests were using `request_hot_reload(FullRestart)` purely as "send any command" (backpressure, owner-gone, payload recovery, wake counting). Gating them would have made real inbox behaviour untested in the default build, so they were migrated to `send_navigation` instead. Only the two genuinely hot-reload-specific tests are feature-gated.

### `flui-binding` → `flui-testing`

`git mv` so history follows. `HeadlessBinding` keeps its name; `AppBinding`/`WidgetsBinding` are untouched. The crate is documented as the workspace's **test-support** package — the obvious home for a future `WidgetTester`, virtual time, fake platform capabilities, replay, and golden helpers.

**On the "runtime libraries must not take a normal dependency on flui-testing" criterion:** this was already structurally true — `flui-widgets`, `flui-material`, `flui-cupertino` and the facade all had it as a dev-dependency only. The work here was **preserving** that through the rename, not establishing it. `docs/workspace-layers.toml` now records the rule explicitly.

### `flui-app::theme` removed — architecture recorded *before* the deletion

"No consumers, so delete it" is the wrong reason and was not used. Zero consumers proves the API can be broken for free; it does not prove the need is absent. **[ADR-0042](https://github.com/vanyastaff/flui/blob/feat/569-package-surface/docs/adr/ADR-0042-theming-ownership.md)** records the target architecture first:

- OS appearance belongs to the **presentation** — `MediaQueryData::platform_brightness`, one window's tree.
- Theme *selection* belongs to the **design system** — `ThemeMode` goes to `flui-material`, with `MaterialApp`.
- The theme lives **in the tree**, published per window, so two windows can differ.
- **No universal `ThemeData` trait** — what is shared is the mechanism, never the tokens.
- **`WidgetsApp` stays design-neutral** — navigation, localization, focus and media information with neither catalog.

`AppTheme` and `AppColorScheme` are deleted outright: no alias, no re-export, no move. `ThemeMode` is deliberately **not** relocated — an unused enum with a new address is relocated debt; it lands with `MaterialApp`. Non-code references (`flui-app/src/lib.rs` module map, `flui-app/README.md`, the rust-studio backlog) are cleaned up, and `just inventory-check` now **fails** if a `theme` module reappears under `crates/flui-app/src/`, with the rule also written into `crates/flui-app/AGENTS.md`.

Follow-up for the app shells: **#573** (`WidgetsApp` / `MaterialApp` / `CupertinoApp`, with tests for theme switching, OS brightness changes, and two windows showing different themes).

### `run_direct` classified, not removed

It has real examples (`direct_render`, `aa_showcase`), and [ADR-0039](https://github.com/vanyastaff/flui/blob/main/docs/adr/ADR-0039-event-loop-affinity-capability.md) slice 2 already owns moving its bootstrap onto `on_ready`. So: documented as an **experimental, direct-engine** API with its three limitations named (no winit backend, no input handling, no damage tracking), the Linux fix tied to that ADR by name, and no event-loop surgery mixed into a package cleanup. Updated in the module docs, the function docs, `flui-app/README.md`, and `flui-app/AGENTS.md`.

## Evidence

**The central risk was a falsely-green matrix.** A passing `cargo build --workspace` is not evidence here, so the gate is `just facade-combos`: each combination is its own cargo invocation against the `flui` package alone, with `--all-targets` so a missing `required-features` is caught. It also asserts via `cargo tree` that `flui-hot-reload` is *absent* from `flui-app`'s default normal graph and *present* with the feature. It runs in the CI `feature-matrix` job (which now installs `just`, so the combination list has exactly one home).

**Red-state verified, then reverted:** removing `required-features = ["cupertino"]` from the cupertino demo makes `facade-combos` fail on the `--no-default-features` run with `unresolved import flui_cupertino`. Both new `inventory-check` guards were likewise verified red before green.

| Gate | Result |
|---|---|
| `just inventory-check` | pass (28 crates, 136 normal edges) |
| `just port-check` | pass (22 triggers + FR-033 + the rest) |
| `just ci` | pass (fmt → inventory → port-check → clippy → 8508 tests → doc-tests → doc-strict) |
| `taplo fmt --check` | pass |
| `typos` | pass |
| `cargo deny check` | advisories / bans / licenses / sources ok |
| `cargo hack clippy --workspace --each-feature --optional-deps` | pass (libs/bins and tests/benches/examples) |
| `just facade-combos` | 13/13 configurations pass in isolation |
| `zizmor .` | no findings |

Isolated facade builds, each `cargo clippy -p flui --locked --all-targets`: `--no-default-features`; `material`; `cupertino`; `material,cupertino`; `localizations`; `material,localizations`; `cupertino,localizations`; `material,cupertino,localizations`; `hot-reload`; `golden`; `serde`; default; `--all-features`.

`cargo nextest run -p flui --features cupertino,localizations` — 31 passed. Added to `just test-ci` and the CI test job, because Material-first defaults would otherwise make `tests/cupertino_demo.rs` CI-dead (same precedent as the existing flui-assets/flui-widgets feature-gated run).

### Cross-target: what was genuinely type-checked vs. `cfg`-structure only

**Type-checked:**
- `x86_64-unknown-linux-gnu` — everything above.
- `wasm32-unknown-unknown` — full workspace minus the 7 documented exclusions, **zero warnings**. This is real coverage of the feature-off path: wasm32 has no desktop runner, so it exercises the seam with `WorkerReload` absent.
- `x86_64-pc-windows-msvc` and `aarch64-apple-darwin` — `cargo clippy -p flui-platform --all-targets` (the repo's cross-typecheck scope), both clean.
- The Android `ScenePlugin` bodies (both real and inert) — type-checked on the host by temporarily neutralising their seven `target_os = "android"` gates; no errors. Reverted.

**`cfg`-structure only, stated plainly:**
- `run_android`'s frame-callback call site. `cargo check --target aarch64-linux-android` cannot run here at all, and not because of this change: `flui-platform`'s Android backend has **4 pre-existing `unsafe_op_in_unsafe_fn` errors** in `platforms/android/memory.rs`, so nothing above it compiles for that target. (Reproduced with an NDK-shim; the file is untouched by this PR. Worth its own issue.)
- `target_os = "ios"` paths — no Apple SDK on this host; `flui-app` for `aarch64-apple-darwin` also stops in `psm`'s C build script, which is why CI's cross-typecheck covers `flui-platform` only.

## Acceptance criteria (#569)

- ✅ Material-only, Cupertino-only, both, and catalog-free configurations compile independently — proven by isolated per-combination builds, not a workspace build.
- ✅ Hot reload absent from normal production graphs unless enabled — `cargo tree` assertion in the gate.
- ✅ The facade offers the documented global-localizations entry point — `flui::localizations` + a live test that builds a `Localizations` with the global delegate.
- ✅ The package is named `flui-testing`, and no public documentation teaches the old name. A repo-wide scan in `check-workspace-inventory.sh` enforces it, exempting only `docs/research`, `docs/plans`, and `docs/audits` — dated snapshots, one of which is the review that *mandated* the rename and would be falsified by rewriting it. Residual mentions: 4 files, all in those directories.
- ✅ Runtime libraries do not gain normal dependencies on `flui-testing` — already true; preserved and now recorded in the layer policy.
- ✅ Parked application surfaces removed or assigned a milestone — `flui-app::theme` removed under ADR-0042 with follow-up #573; `run_direct` explicitly classified as experimental with its fix owned by ADR-0039.
- ✅ cargo-hack proves feature wiring without accidental unification — both `--each-feature` passes plus the isolated combination builds.

**Deferred, explicitly:** "move test-only helpers, fake platform capabilities, virtual time, replay and golden support toward `flui-testing`" is a design direction in the issue body, not one of the seven acceptance criteria. No existing helper is moved here — that is behavioural surgery across several crates and does not belong in a package-surface change. `flui-testing` is documented and shaped as their home, which is what this PR owes them.

## Tactical decisions

- **`golden = ["material", "cupertino"]`** rather than an empty feature. The golden suite renders both demo trees; a `golden` build without them would silently cover less than its name claims.
- **`just facade-combos` owns the combination list**, and CI installs `just` to call it, instead of duplicating the list in YAML where the two would drift.
- **`ScenePlugin`/`WorkerReload` are scoped to their consuming runner** (`target_os` cfgs mirroring `run_android`/`run_desktop`) rather than carried everywhere behind `expect(dead_code)`, which is why the wasm build is warning-free.
- **The stale-name guard lives in `check-workspace-inventory.sh`**, not `port-check.sh`: it is a package-identity fact, matching where the ADR-0028/ADR-0041 dependency-graph rules already live.
- **The crate-level Material doc example is emitted via `#[cfg_attr(feature = "material", doc = …)]`.** A doctest does not inherit the crate's features as `cfg`, so an inline `# #[cfg(...)]` cannot work; without this, `cargo test --doc --no-default-features` would fail on a supported configuration.
- **ADRs were updated where they name a live path or crate; `docs/research`, `docs/plans` and `docs/audits` were left untouched** as dated snapshots.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: crates/flui-app/src/app/hot_reload.rs [hunk 1]
```diff
@@ -0,0 +1,317 @@
...
+    impl WorkerReload {
+        pub(crate) fn from_config(config: &AppConfig) -> Self {
+            // A configured worker plugin that silently does nothing is worse
+            // than a missing feature, so say so once at bootstrap.
+            if config.worker_plugin_path.is_some() {
+                tracing::warn!(
+                    "a worker plugin path is configured, but flui-app was built without the \
+                     `hot-reload` feature — the plugin will not be loaded"
+                );
+            }
```
[the remark this answers is not in the document]
Comment (vanyastaff) [reply crates/flui-app/src/app/hot_reload.rs]: Fixed in 72c4a556. The feature-off path now checks FLUI_WORKER_PLUGIN with var_os and emits a warning. The typed worker_plugin_path field and with_worker_plugin_path builder are also cfg(feature = "hot-reload"), so code cannot explicitly configure an omitted capability.

File: crates/flui-app/Cargo.toml [hunk 2]
```diff
@@ -21,6 +21,14 @@ android = []
 ios = []
 web = []
 
+# === Development capabilities ===
+# Hot reload is a development capability, not part of an ordinary production
+# graph: with this feature off, `flui-hot-reload` is absent from
+# `cargo tree -p flui-app` and no target of this crate imports it. Everything
+# that would touch it goes through `app::hot_reload`, which has a real and an
+# inert implementation; the inert one names no `flui_hot_reload` item at all.
+hot-reload = ["dep:flui-hot-reload"]
```
[the remark this answers is not in the document]
Comment (vanyastaff) [reply crates/flui-app/Cargo.toml:32]: Fixed in 72c4a556. hot-reload-counter-host now enables flui-app/hot-reload explicitly. just facade-combos also asserts through cargo tree that the host activates that dependency feature, so the documented flui run workflow cannot silently select the inert seam again.
